source "http://rubygems.org"

gem "sinatra", :require => "sinatra/base"
gem "sinatra-contrib", :require => "sinatra/contrib"
gem "sinatra-reloader", :require => "sinatra/reloader"
gem "sinatra-session", :require => "sinatra/session"
gem "mongo"
gem "bson_ext"
gem "vmc"
gem "json"
gem "pdfkit"
gem "net-ldap"
